# Generated by Django 4.0.1 on 2022-01-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodvector',
            name='playlist_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
