# Generated by Django 4.0.1 on 2022-01-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_moodvector_playlist_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodvector',
            name='x_end',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='moodvector',
            name='x_start',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='moodvector',
            name='y_start',
            field=models.FloatField(),
        ),
    ]
