# Generated by Django 4.0.1 on 2022-01-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_moodvector_x_end_alter_moodvector_x_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodvector',
            name='y_end',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
