version: '3.9'

services:
  backend:
    container_name: django_backend
    build: ./backend
    #platform: linux/amd64
    restart: always
    command: bash -c "pip install -r requirements.txt && python manage.py
      makemigrations && python manage.py migrate && python manage.py runserver
      0.0.0.0:8000"
    env_file: .env
    volumes:
      - ./backend:/app
      - ./frontend/dist/static:/app/frontend/static
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: react_frontend
    build: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install && npm run dev"

  db:
    container_name: postgres_container
    image: postgres
    #platform: linux/amd64
    restart: always
    environment:
      POSTGRES_DB: djangodb
      POSTGRES_USER: djangoUser
      POSTGRES_PASSWORD: securepwd
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d djangodb -U djangoUser" ]
      interval: 10s
      timeout: 3s
      retries: 7

volumes:
  pgdata: null
