# Generated by Django 4.0.1 on 2022-01-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('album_id', models.CharField(max_length=50)),
                ('album_name', models.CharField(max_length=200)),
                ('artist_id', models.CharField(max_length=50)),
                ('artist_name', models.CharField(max_length=200)),
                ('key', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('tempo', models.IntegerField()),
                ('duration', models.PositiveBigIntegerField()),
                ('time_signature', models.IntegerField()),
                ('ft_danceability', models.FloatField()),
                ('ft_energy', models.FloatField()),
                ('ft_loudness', models.FloatField()),
                ('ft_speechiness', models.FloatField()),
                ('ft_acousticness', models.FloatField()),
                ('ft_instrumentalness', models.FloatField()),
                ('ft_liveness', models.FloatField()),
                ('ft_valence', models.FloatField()),
            ],
        ),
    ]
