# Generated by Django 4.0.1 on 2022-01-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='seed_genre',
        ),
        migrations.RemoveField(
            model_name='track',
            name='arousal',
        ),
    ]
