# Generated by Django 4.0.1 on 2022-01-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(max_length=300),
        ),
    ]
