# Generated by Django 4.0.1 on 2022-01-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_usertrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='acousticness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='danceability',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='energy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='instrumentalness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='key',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='liveness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='loudness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='mode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='popularity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='speechiness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='tempo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='time_signature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='valence',
            field=models.FloatField(null=True),
        ),
    ]
