# Generated by Django 4.0.1 on 2022-01-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_alter_track_acousticness_alter_track_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cluster',
            field=models.IntegerField(null=True),
        ),
    ]
