# Generated by Django 4.0.1 on 2022-01-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_track_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='cluster',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
